CREATE TABLE [dbo].[Comment]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[PostId] INT NOT NULL FOREIGN KEY REFERENCES [Post](Id),
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES [User](Id),
	[Content] NVARCHAR(1000) NOT NULL,
	[Score] INT NOT NULL DEFAULT 0,
	[CreatedDateTimeUtc] DATETIME2 NOT NULL
)
