CREATE TABLE [dbo].[Post]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES [User](Id),
	[Title] NVARCHAR(500) NOT NULL,
	[Summary] NVARCHAR(1000) NOT NULL,
	[Content] NVARCHAR(MAX) NOT NULL,
	[CreatedDateTimeUtc] DATETIME2 NOT NULL
)
