CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[DisplayName] NVARCHAR(500) NOT NULL,
	[AADObjectId] UNIQUEIDENTIFIER NOT NULL UNIQUE CLUSTERED,
	[CreatedDateTimeUtc] DATETIME2 NOT NULL
)